<a href="https://colab.research.google.com/github/amaysaxena02/AIML-with-GEN-AI/blob/main/Numpy_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
sample_arr = np.arange(1,11)

In [ ]:
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_arr[2]
sample_arr[0:4]

array([1, 2, 3, 4])

In [ ]:
sample_arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(sample_mat)

numpy.ndarray

In [ ]:
sample_mat[1:2]

array([[4, 5, 6]])

In [ ]:
sample_mat[1][2]

np.int64(6)

In [ ]:
sample_mat[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
sample_mat[1,1:]

array([5, 6])

In [ ]:
sample_mat[0:5]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Broadcasting, Slice, Copy

In [ ]:
sample_arr[0:3] = 400
sample_arr

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
print(id(sample_arr[0:5]))
slice_of_sample_arr = sample_arr[0:5]
s = slice_of_sample_arr
print(id(slice_of_sample_arr))
print(id(sample_arr))
print(id(s))

136295315835280
136295315835280
136295317382384
136295315835280


In [ ]:
slice_of_sample_arr[:] = 100
slice_of_sample_arr

array([100, 100, 100, 100, 100])

In [ ]:
sample_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
sample_arr_copy = sample_arr.copy()
sample_arr_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
print(id(sample_arr_copy))
print(id(sample_arr))

136295315839024
136295317382384


In [ ]:
sample_arr_copy[:]=200
sample_arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
sample_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

differece b/w range and arange functions

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
boolean_arr = arr > 5
print(boolean_arr)
print(type(boolean_arr))

[False False False False False  True  True  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr<5]

array([1, 2, 3, 4])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
b = np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
print("add",np.add(a,b))
print("subtract",np.subtract(a,b))
print("multiply",np.multiply(a,b))
print("divide",np.divide(a,b))

add [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
subtract [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
multiply [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400 441 484 529 576]
divide [nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipython-input-176-334374931.py:4: RuntimeWarning: invalid value encountered in divide
  print("divide",np.divide(a,b))


In [ ]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.dot(a,100)
b

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
cross_product_3d = np.cross(x, y)
print(f"Cross product of 3D vectors: {cross_product_3d}")

Cross product of 3D vectors: [-3  6 -3]


implement bubble sort in python


In [ ]:
print(a/a)
print(1/a)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


/tmp/ipython-input-181-779480695.py:1: RuntimeWarning: invalid value encountered in divide
  print(a/a)
/tmp/ipython-input-181-779480695.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/a)


In [ ]:
coefficient = [12,3,4,5,10]
polynomialExp = np.poly1d(coefficient)
print("type of polynomial",type(polynomialExp))
print(polynomialExp)
x = 2
result = polynomialExp(x)
print("result",result)

type of polynomial <class 'numpy.poly1d'>
    4     3     2
12 x + 3 x + 4 x + 5 x + 10
result 252


In [ ]:
a = np.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120)))
print("a: \n",a)
b = np.transpose(a)
print("trasnpose of a: \n",b)

a: 
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
trasnpose of a: 
 [[ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]
 [ 40  80 120]]


In [ ]:
a = np.identity(10)
print("10*10 identity matrix: \n",a)
print(type(a))

10*10 identity matrix: 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [ ]:
a = np.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(2,3,4,5)))
b = np.hsplit(a,2)
print("a \n",a)
print("b \n",b)

a 
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [  2   3   4   5]]
b 
 [matrix([[ 10,  20],
        [ 50,  60],
        [ 90, 100],
        [  2,   3]]), matrix([[ 30,  40],
        [ 70,  80],
        [110, 120],
        [  4,   5]])]


In [ ]:
c = b[0]
d = b[1]
print("c \n",c)
print("d \n",d)

c 
 [[ 10  20]
 [ 50  60]
 [ 90 100]
 [  2   3]]
d 
 [[ 30  40]
 [ 70  80]
 [110 120]
 [  4   5]]
