<a href="https://colab.research.google.com/github/amaysaxena02/AIML-with-GEN-AI/blob/main/Numpy_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
type(my_list)

list

In [ ]:
import numpy as np
myNpList = np.array(my_list)
myNpList

array([1, 2, 3])

In [ ]:
type(myNpList)

numpy.ndarray

In [ ]:
sample_lsit_of_list = ([[1,2,3],[4,5,6],[7,8,9]])
sample_lsit_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(sample_lsit_of_list)

list

In [ ]:
sample_matrix = np.array(sample_lsit_of_list)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(sample_matrix)

numpy.ndarray

In [ ]:
np.arange(1,40,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [ ]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
c = np.random.rand(4)
c

array([0.0808255 , 0.2050614 , 0.09149957, 0.18173966])

Random function is used to generate uniformly distributed numbers between 0 and 1

In [ ]:
type(c)

numpy.ndarray

Normal distribution center around 0

In [ ]:
b = np.random.randn(3,4)
b

array([[-0.22031444,  0.80490905,  0.06762159, -0.99266094],
       [-0.86927036, -0.41019918,  0.71160902, -1.16434381],
       [-0.32828562, -0.64056951, -0.6311042 , -0.96805675]])

In [ ]:
b.shape

(3, 4)

In [ ]:
b.dtype

dtype('float64')

In [ ]:
random_arr = np.random.randint(10,50,5)
random_arr

array([45, 10, 25, 47, 42])

In [ ]:
random_arr.max()

np.int64(47)

In [ ]:
random_arr.shape

(5,)

In [ ]:
type(random_arr.shape)

tuple